GET_PAGE_READY_STATE = "return document.readyState"
SCROLL_TO_TOP = "window.scrollTo(0, 0);"
SCROLL_TO_BOTTOM = "window.scrollTo(0,Math.max(document.documentElement.scrollHeight,document.body.scrollHeight,document.documentElement.clientHeight));"
SCROLL_INTO_VIEW = "arguments[0].scrollIntoView(arguments[1]);"
CLICK_ELEMENT = "arguments[0].click();"
GET_TEXT_CONTENT_FOR_ELEMENT = "return arguments[0].textContent;"
SET_ATTRIBUTE_TO_ELEMENT = "arguments[0].setAttribute(arguments[1], arguments[2]);"
SET_TEXT_TO_ELEMENT = "arguments[0].innerText = arguments[1]"
BORDER_ELEMENT = "arguments[0].style.border='3px solid red';"
SET_FOCUS = "arguments[0].focus();"
SELECT2_SELECT_BY_TEXT = "var value = $(arguments[0]).find('option:contains('+arguments[1]+')').val();$(arguments[0]).select2('val', value);"
SELECT2_SELECT_BY_VALUE = "$(arguments[0]).select2('val', arguments[1]);"
SELECT2_GET_SELECTED_OPTIONS = "return $(arguments[0]).select2('data').text;"
